### ISSUE TITLE
Run rq-scheduler in same process as rq

### ISSUE THREAD

**Issue by sandlerben** [ui/rq-scheduler#105]
I'm using Heroku for deployments so I'm limited to one worker process. Right now, I am running this code as my worker:

```python
"""Initializes a slim rq task queue. File taken from
http://python-rq.org/patterns/"""

import os
import urlparse
from redis import Redis
from rq import Worker, Queue, Connection

listen = ['high', 'default', 'low']

redis_url = os.getenv('REDISTOGO_URL') or 'http://localhost:6379'
if not redis_url:
    raise RuntimeError('Set up Redis To Go first.')

urlparse.uses_netloc.append('redis')
url = urlparse.urlparse(redis_url)
conn = Redis(host=url.hostname, port=url.port, db=0, password=url.password)

if __name__ == '__main__':
    with Connection(conn):
        worker = Worker(map(Queue, listen))
        worker.work()
```
Can I run the scheduler in this same worker process?

**Comment by selwin** [comment]
Unfortunately, it's not supported out of the box. Though you could kind of get around it by writing a custom worker that periodically runs the scheduler function.

**Comment by sandlerben** [comment]
Are there any examples I could look to?

**Comment by selwin** [comment]
You could take a look at this custom worker which uses gevent for
concurrency to see how it overrides certain methods on the base worker
class. https://github.com/zhangliyong/rq-gevent-worker

Yours should be much simpler though, I imagine you could just run scheduler
after `worker.perform_job` or similar.


Win~

**Comment by sandlerben** [comment]
This might be a bit of a hack, but how about something like this:

`python run_worker.py & rqscheduler && fg`

Based on http://stackoverflow.com/a/5553774/3624201

**Comment by westonplatter** [comment]
@sandlerben did that work for you?

**Comment by sandlerben** [comment]
I don't remember :( ... I would say probably
