### ISSUE TITLE
Current (0.5.1) release is more than a year old

### ISSUE THREAD

**Issue by robert-osborne** [ui/rq-scheduler#106]
A number of features and bug fixes in the master code base are not available by pip install.

**Comment by madisvain** [comment]
I also noticed this when I wanted to schedule jobs with an id. It would be great to have a new release with the features and bugfixes.

**Comment by docc** [comment]
+1

**Comment by phalgun** [comment]
+1

**Comment by selwin** [comment]
Sorry for the delay. I'm just waiting for https://github.com/ui/rq-scheduler/pull/80 to be updated so we can make a 0.6 release with crontab feature baked in.

**Comment by selwin** [comment]
Version 0.6 is now on PyPI: https://pypi.python.org/pypi/rq-scheduler
