### ISSUE TITLE
How can I confirm scheduled jobs are being queued?

### ISSUE THREAD

**Issue by cmanallen** [ui/rq-scheduler#108]
@selwin Is there some debug output I can look at that shows the scheduled job has been run?

How I'm scheduling the jobs:
```python
scheduler.schedule(
    func=disable_products, interval=1, scheduled_time=datetime.utcnow(),
    repeat=None)
print scheduler.get_jobs() # [Job(u'ee309ceb-46d0-4817-8be2-cf1d41f0428e', enqueued_at=datetime.datetime(2016, 2, 10, 21, 50, 48))]
```

How I'm running the rqscheduler script:
```
docker-compose run web rqscheduler --host redis --port 6379 --db 1 --interval 1
```

The cursor just blinks endlessly after executing the above command.  Is that normal behavior?

**Comment by selwin** [comment]
You can use an RQ monitoring system like https://github.com/ui/django-rq to monitor your jobs.
