### ISSUE TITLE
Jobs scheduled via cron expire automatically after 500 sec if the time between two job executions exceeds 500 sec

### ISSUE THREAD

**Issue by csaba-stylight** [ui/rq-scheduler#116]
Jobs scheduled via `Scheduler.cron` expire automatically after 500 sec if the time between two job executions exceeds 500 sec. (see #115)

This makes scheduling jobs via `Scheduler.cron` kinda meaningless (unless they are executed at least every 500 sec).

**Comment by lechup** [comment]
We have #115 merged - we can close this one @csaba-stylight ?

**Comment by selwin** [comment]
Fixed in #115
