### ISSUE TITLE
Chnaging intervall scheduler checks for tasks

### ISSUE THREAD

**Issue by wpxgit** [ui/rq-scheduler#129]
So far i can see the scheduler checks every minute for new tasks.

I like to queue tasks faster after they had been added to schedule and also to queue a task every 5 seconds.

It seems that the scheduler-intervall is hard coded at this line:
https://github.com/ui/rq-scheduler/blob/master/rq_scheduler/scheduler.py#L23

Must i consider something if i like to change the value in the code e.g. to 5 seconds?

Whats the best way to make it configurable?

Thanks!

**Comment by Kilte** [comment]
@wpxgit, rqscheduler accepts [`-i` argument](https://github.com/ui/rq-scheduler/blob/master/rq_scheduler/scripts/rqscheduler.py#L24).

**Comment by wpxgit** [comment]
Thanks Kilte - don't know wyh i haven't found these settings - Thanks!
