### ISSUE TITLE
Periodic Schedule: Interval Parameter Issue

### ISSUE THREAD

**Issue by ryanermita** [ui/rq-scheduler#163]
I'm having an issue about the `interval` parameter of rq scheduler.
Project spec
- Django 1.10.6
- django-rq 0.9.6
- rq-scheduler 0.7.0
- Python 2.7.13

```
import django_rq
from datetime import datetime

scheduler = django_rq.get_scheduler("default")
scheduler.schedule(
    scheduled_time=datetime.utcnow(),
    func=some_function,
    args=[],
    kwargs={},
    interval=30,
    repeat=None
)
scheduler.run()
```

This scheduler run but it does not work as intended. The function run every minute and not as specified on the interval parameter.

I checked the `scheduler.__dict__` using python console and found out that there is a `_interval` attribute with the value of 60. It seems the scheduler uses this interval and not the interval on the schedule parameter.

`{'_interval': 60, 'connection': Redis<ConnectionPool<Connection<host=localhost,port=6379,db=0>>>, 'queue_name': 'default', 'log': <logging.Logger object at 0x10213e250>}`

as of now my work around is to set this `_interval` before running my scheduler.

`scheduler._interval = 30`

Is there any cleaner way to make this work. Thank you.

**Comment by mojeto** [comment]
Hi @ryanermita,
Scheduler has two different intervals. 
The first interval is how often scheduler checks Redis and push scheduled jobs to correct queues. - implemented as an active `while(True)` loop with `sleep(interval)` call. 
Default value of that interval is **60 seconds** 
The second interval is per scheduled job and sets how often job should run. 
To make your example work scheduler first interval (**refresh interval**) has to be smaller than or equal to lowest job interval.

To make sure your job starts at proper time your scheduler refresh interval has to be divisor of your job interval (for example 30, 15, 10, 5 etc.) 
If you have more scheduled jobs your scheduler refresh interval has to be divisor of all of them.

To fix your example:
```
import django_rq
from datetime import datetime

scheduler = django_rq.get_scheduler("default", interval=15)  # scheduler refresh interval 
scheduler.schedule(
    scheduled_time=datetime.utcnow(),
    func=some_function,
    args=[],
    kwargs={},
    # job specific interval value 
    interval=30,  # should be always divisible by scheduler refresh interval
    repeat=None
)
scheduler.run()
```
If you use django_rq commands you shall specify this interval as a command parameter
`manage.py rqscheduler --interval 15`

Note:
If my project requires some jobs to run every couple of seconds I use scheduler refresh interval 1 (schedule jobs every second) so I'm sure all jobs starts in the time they should.

**Comment by ryanermita** [comment]
I understand it better now. Thank you for your response @mojeto
