### ISSUE TITLE
How to set Job dependency?

### ISSUE THREAD

**Issue by pacifictoy** [ui/rq-scheduler#53]
Hello,

RQ allows setting up queues that has job A, and job B will depend on job A (it will not run until job A is finished).

Looking at rq-scheduler source code, seems like this feature is not usable....
Is it?

if not,
Is there a general thought / suggestion on the approach to include this feature in rq-scheduler?

Thanks!

**Comment by ggold6** [comment]
Probably late for @pacifictoy but for future reference: 
I just tackled this by using RQ-schduler to run a job that runs a procedure which itself calls another job + its dependencies .. Not particularly direct, but works like a charm, really very little overhead.
@selwin , if this is a resonable solution, should this issue be closed?

**Comment by selwin** [comment]
Sorry for the late reply @pacifictoy, I totally missed this thread. I don't think this is an issue that will be tackled in the near future.

You can workaround this as @ggold6 suggested, write a new function that calls your two other functions one after another.
