### ISSUE TITLE
Disable repeated output of the 'Checking for scheduled jobs...' message.

### ISSUE THREAD

**Issue by berimor** [ui/rq-scheduler#61]
Hi,

the current version writes 'Checking for scheduled jobs...' to the INFO log repeatedly on every call to enqueue_jobs(). This is extremely annoying and costs processor time, especially if the check interval is very small (e.g. 0.1 second).  

I know that this behaviour has been explicitly introduced in the commit 40c8228a4aac25a6a60a2d581e7e223f1a08aa0e: self.log.info('Checking for scheduled jobs...'). But I don't know the reason for that. I think, this message should be logged only in DEBUG.

Can you change it to DEBUG or should I make a PR?

**Comment by selwin** [comment]
I think the current setting is okay for most people. I agree that in your use case (1 check every 0.1 second) it may be a bit verbose, you can configure logging filters for this: https://docs.python.org/2/library/logging.html#filter-objects
