### ISSUE TITLE
options to RQ like result_ttl, etc.

### ISSUE THREAD

**Issue by YAmikep** [ui/rq-scheduler#63]
Hi,

I am using ``enqueue_in`` and there is no way to use RQ options like ``result_ttl=0`` to discard the results immediately, correct?

Thanks
Michael

**Comment by selwin** [comment]
The `enqueue_in` [method](https://github.com/ui/rq-scheduler/blob/master/rq_scheduler/scheduler.py#L109) takes `*args` and `**kwargs` which is then passed to `Job.create` [here](https://github.com/ui/rq-scheduler/blob/master/rq_scheduler/scheduler.py#L79) so `result_ttl` should be respected.
