### ISSUE TITLE
Schedule via crontab definition.

### ISSUE THREAD

**Issue by meunierd** [ui/rq-scheduler#65]
I was hoping to be able to schedule recurring jobs via a cron-definition rather than just an interval. Is this a desirable feature?

**Comment by selwin** [comment]
Yes, I think this is a good idea

**Comment by sandywater** [comment]
+1

**Comment by sam-untapt** [comment]
:+1:

**Comment by selwin** [comment]
PR welcome :)

**Comment by petervtzand** [comment]
I created a PR!
https://github.com/ui/rq-scheduler/pull/80

**Comment by himmelarthur** [comment]
:+1:

**Comment by lechup** [comment]
@meunierd this one can be closed as #80 was merged into master.

**Comment by selwin** [comment]
Fixed in https://github.com/ui/rq-scheduler/pull/80
