### ISSUE TITLE
All jobs may have to be canceled in _install_signal_handlers

### ISSUE THREAD

**Issue by lukhnos** [ui/rq-scheduler#66]
I use rq-scheduler to schedule a periodic job that runs forever. However, if I stop the scheduler process and start the scheduler again without flushing Redis, I find the previous periodic job will still be enqueued by the new process. So now after each interval, I have two jobs enqueued each time.

The job is scheduled with:

```python
scheduler.schedule(
    scheduled_time=datetime.datetime.now(),
    func=some_func,
    interval=some_interval
)
```
My current solution is to cancel all jobs in the signal handler. I made a `Scheduler` subclass, replicated the `_install_signal_handlers` method, and added two lines inside the method:

```python
def _install_signal_handlers(self):
    def stop(signum, frame):
        # Clean up the scheduler job.
        for job in scheduler.get_jobs():
            scheduler.cancel(job)
    # ...
```

Does this look like a correct solution, or could there be any problems if we cancel jobs in the signal handler?

Thank you!

**Comment by lost-theory** [comment]
I'm not sure if this is the way rq-scheduler is meant to be used... Why are your jobs enqueued a second time when the scheduler restarts?  This doesn't happen for me.

The scheduler's job is to check the existing schedule and enqueue jobs at the appropriate time. The schedules are persisted in redis, so there's no need to repeatedly add/clear them each time the scheduler runs or exits.

**Comment by lukhnos** [comment]
@lost-theory I have a custom scheduler script that both schedules the task at start and also runs the scheduler. I must have failed to notice the persistence of schedule by design, hence my misunderstanding. Thanks for pointing that out!
