### ISSUE TITLE
No logs, not moving jobs to queue

### ISSUE THREAD

**Issue by linkyndy** [ui/rq-scheduler#69]
I started a scheduler instance on the default queue, but I received no output on the terminal. The process was still alive, but why wasn't there any output?

Then I've enqueued a task using `enqueue_in` and a timedelta of 5 seconds. I haven't received again no output on the terminal, but I could see the job with `get_jobs()`. After the timedelta expired, the job disappeared from `get_jobs()`, but it didn't show up in the default RQ queue.

Am I missing something or doing something wrong?

**Comment by lost-theory** [comment]
Looks like you can use `-v` to get verbose logs:

https://github.com/ui/rq-scheduler/blob/46b29da/rq_scheduler/scripts/rqscheduler.py#L45-L49

Can you post your code you're using to enqueue? Are you running a worker? Maybe it got picked up by a worker.

Another thing I've found useful in debugging rq / rq-scheduler is to use `redis-cli monitor` to watch all the redis commands as-they-happen.

**Comment by linkyndy** [comment]
Seems that I have no `-v` flag available:

```bash
(venv)linkyndys-MacBook-Air:prji linkyndy$ rqscheduler --help
usage: rqscheduler [-h] [-H HOST] [-p PORT] [-d DB] [-P PASSWORD] [--url URL]
                   [-i INTERVAL] [--path PATH] [--pid FILE]

Runs RQ scheduler

optional arguments:
  -h, --help            show this help message and exit
  -H HOST, --host HOST  Redis host
  -p PORT, --port PORT  Redis port number
  -d DB, --db DB        Redis database
  -P PASSWORD, --password PASSWORD
                        Redis password
  --url URL, -u URL     URL describing Redis connection details. Overrides
                        other connection arguments if supplied.
  -i INTERVAL, --interval INTERVAL
                        How often the scheduler checks for new jobs to add to
                        the queue (in seconds).
  --path PATH           Specify the import path.
  --pid FILE            A filename to use for the PID file.
```

I've installed the latest RQ Scheduler, so I find this weird. I've checked the sources and logs are set up exactly like in the RQ project, and those work as expected.

Regarding your second suggestion, `redis-cli monitor` is indeed very helpful, thank you! I found out that I was erroneously passing a `Queue` object, not the queue name when fetching a `Scheduler`.

**Comment by lost-theory** [comment]
Oh, I see. The latest release on pypi is 0.5.0 from 2014-04-04, while that verbose flag [was added 2014-06-28](https://github.com/ui/rq-scheduler/commit/c2e2f1). @selwin do you plan on releasing a new version to pypi?

**Comment by linkyndy** [comment]
So that's why. Anyways, shouldn't the default behavior be to display something to the user? At least the basic things RQ does (process started, job received and scheduled, job moved to queue etc.).

**Comment by selwin** [comment]
There were some logging changes in the 0.5.0 release but as far as I know, the start up process is displayed to the user, the message that rq-scheduler is waking up to enqueue jobs should also be displayed. 

Could you try running version 0.4 to ensure that there's nothing in your local configuration that prevents the logs from showing up?

**Comment by selwin** [comment]
@lost-theory yeah. I'll try to release a new bugfix version this weekend.

**Comment by linkyndy** [comment]
@selwin I tried installing 0.4.0 and it's the same: no output. What should I look for? I mention that RQ output works.

**Comment by Sshuichi** [comment]
Same problem here I guess ..

**Comment by iafilatov** [comment]
I think [this change in rq](https://github.com/nvie/rq/commit/b828078dde8cdc57f66f5333af497af6da8fd2e4) broke the logging in rq_scheduler. The scheduler relies on `setup_loghandlers()` which no longer configures the root logger, just the `rq.worker`. But the scheduler logs to `rq_scheduler.sheduler`, which is left unconfigured. I think the best approach for now would be to handle logger configuration independently.

**Comment by selwin** [comment]
@iafilatov thanks for narrowing down the root cause of this issue. Do you mind making a PR to configure the log handler for rq.scheduler ?

**Comment by iafilatov** [comment]
Please check out if #86 is ok.
