### ISSUE TITLE
Pass description (and possibly other args) to Job.create()

### ISSUE THREAD

**Issue by ydaniv** [ui/rq-scheduler#71]
Currently there's no way to pass `description` argument to rq's `Job.create()`.

**Comment by cosminstefanxp** [comment]
+1

I'm mostly interested in passing an id so I can create a kind of 'singleton' behaviour for scheduled tasks over app restarts. 

@ui

**Comment by cosminstefanxp** [comment]
I also think other Job related params could be useful. Examples:

- `id` - for quickly checking the status of a scheduled job, across app restarts
- `ttl` - so you can make sure that an enqueued, but not yet run job does not become queued twice

**Comment by selwin** [comment]
I think we should support passing in params that are supported by "queue.enqueue()" call, provided that they make sense.

PR welcome :)

**Comment by ydaniv** [comment]
:+1:
