### ISSUE TITLE
rq-scheduler 0.5.1 is not installable with Python inside Ubuntu 12.04

### ISSUE THREAD

**Issue by therealmarv** [ui/rq-scheduler#72]
The package format for rq-scheduler seems to new for the ancient Python 2.7.3 inside Ubuntu 12.04. So when trying to install it wit `pip install rq-scheduler` it installs version 0.5.0 and not the newest one.

I've found a workaround for that: Update pip itself `pip install -U pip` and then install rq-scheduler `pip install rq-scheduler`.

You maybe want to mention it in your docs. No problem with new python versions like in Ubuntu 14.04.

**Comment by selwin** [comment]
Strange, I've never seen a problem like this before. Did you try updating pip to the newest version before performing the install?

**Comment by therealmarv** [comment]
This error is reproducable (only tried with virtualenv) when using the newest Ubuntu 12.04 own Python. After updating pip itself it will install the newest version 0.5.1 from pypi

**Comment by selwin** [comment]
Yeah, that means it's a bug in pip itself. I'm going to close this issue. Thanks for the report!

**Comment by therealmarv** [comment]
:+1: just wanted to let you know! ;)
