### ISSUE TITLE
No error shows, but no job work in scheduler

### ISSUE THREAD

**Issue by mingissb** [ui/rq-scheduler#76]
Hello,
I tried to this:
"""
unaware = datetime.datetime.utcnow()+ timedelta(minutes=481) # my timezone is 480min before utc
scheduler = Scheduler(connection=conn)
scheduler.schedule(
    scheduled_time=unaware, # Time for first execution, in UTC timezone
    func=reportemail,                     # Function to be queued
    args=[],             # Arguments passed into function when executed
    kwargs={},         # Keyword arguments passed into function when executed
    interval=30,                   # Time before the function is called again, in seconds
    repeat=3                      # Repeat this number of times (None means repeat forever)
)
"""

and I also tried:

"""
scheduler = Scheduler(connection=conn)
scheduler.schedule(
    scheduled_time= datetime.datetime.now(), # Time for first execution, in UTC timezone
    func=reportemail,                     # Function to be queued
    args=[],             # Arguments passed into function when executed
    kwargs={},         # Keyword arguments passed into function when executed
    interval=30,                   # Time before the function is called again, in seconds
    repeat=3                      # Repeat this number of times (None means repeat forever)
)
"""
Both of them work nothing.
Please tell me how to fix it.
Thank you in advance.

**Comment by mingissb** [comment]
And as for "You'll have to put in datetime in UTC."
What's the meaning "put in datetime in UTC"? what should I do in codes ?

**Comment by andrewshkovskii** [comment]
Use datetime.utcnow() .

**Comment by selwin** [comment]
What @andrewshkovskii said is right :)
