### ISSUE TITLE
How to re-schedule a job that is in the scheduler

### ISSUE THREAD

**Issue by niks3089** [ui/rq-scheduler#78]
I have a job to schedule in 2 minutes. After a minute I want to  re-schedule the same job after 2 minutes,
Following is what I have tried (Its a snippet of actual piece)

            scheduler = django_rq.get_scheduler('default')
            job = channel_to_job_dict.get(item['channel'])
            if job is None:
                print "schedule a job "
                job = scheduler.enqueue_in(timedelta(seconds = 10),
                        handle_unresponsive_antik, item['channel'])
                # Enqueue the job in a dict
                channel_to_job_dict[item['channel']] = job 
            elif job in scheduler:
                # Re-schedule after 10 seconds
                print "rescheduling job"
                scheduler.cancel(job);
                scheduler.enqueue_job(job);

**Comment by jmmills** [comment]
I'm not exactly understanding your use case here, but I think what you are looking for is ```change_execution_time```

**Comment by selwin** [comment]
@niks3089 you can pass a `repeat` argument to `scheduler.schedule` to repeat jobs, or use `change_execution_time`, as per @jmmills ' suggestion.
