### ISSUE TITLE
Add queue_name options to enqueue_in, and enqueue_at

### ISSUE THREAD

**Issue by jmmills** [ui/rq-scheduler#84]
It would be nice if there was parity between these functions and enqueue/schedule.

**Comment by selwin** [comment]
Yes, indeed. Pull request welcome :)

**Comment by jmmills** [comment]
Upon thinking about it, doesn't it seem to make more sense the rq-scheduler should sub-class Queue? It is after all just a scheduled queue...

So instead of something like this:

     from rq import Queue
     from redis import Redis

     def job():
       pass

     q = Queue('magic', connection=Redis())
     q.enqueue(job)

Something like this:

     from rq.scheduler import Scheduler
     from redis import Redis
     from datetime import timedelta

     def job():
       pass

     q = Scheduler('magic', connection=Redis())
     q.enqueue(job)
     q.enqueue_in(timedelta(seconds=30), job)

**Comment by selwin** [comment]
The underlying implementation of `Scheduler` and `Queue` are very differently so it wouldn't make sense.

There's a plan to integrate `rq-scheduler` into `RQ` and there's even a [branch](https://github.com/nvie/rq/tree/scheduler-integration) for it, but it has been languishing for quite a while. When the integration is complete, we plan on integrating the APIs into `Queue`, like you suggested. So you'll be able to do things like:
```python
queue.enqueue_in(...)
queue.enqueue_at(...)
queue.schedule(...)
```

**Comment by jmmills** [comment]
Awesome, then there is overlap between this _want_ versus and that effort. I'll close this out.

Once the scheduling is included in the queue object the queue name would be more "declarative(?)":

```
mpeg = Queue('mpeg')
mpeg.enqueue_at(datetime(2020, 1, 1, 3, 4), transcode, file)
```

IMHO is much better than:

```
mpeg_queue_name = 'mpeg'
mpeg = Queue(mpeg_queue_name)
mpeg_scheduler = Scheduler(mpeg_queue_name)
mpeg_scheduler.enqueue_at(...)
```

How do you guys normally communicate your dev efforts, through just GitHub? I'd like to help out more with the project.

**Comment by selwin** [comment]
Yeah, we don't have any other method of communication really. Just through Github Issues and Pull Requests :)
