### ISSUE TITLE
Question: why expire the scheduler key?

### ISSUE THREAD

**Issue by Microserf** [ui/rq-scheduler#88]
Can someone enlighten me as to what is the purpose of expiring the scheduler key?

We've created a script that does everything `Scheduler.run()` does, but in addition, it processes another type of job during each iteration of the master `while True` loop:

```
        scheduler = get_scheduler(name=queue, interval=options.get('interval'))

        scheduler.log.info('Running RQ scheduler...')
        scheduler.register_birth()
        scheduler._install_signal_handlers()
        try:
            while True:
                # Enqueue `rq-scheduler`'s scheduled jobs
                scheduler.enqueue_jobs()
                time.sleep(scheduler._interval)

                # Perform another scheduling task here
                do_task_b()
        finally:
            scheduler.register_death()

```

If my understanding is correct, the top portion of the `while True` loop checks for rq scheduling jobs which are due, enqueues any as necessary, then sleeps `scheduler._interval` seconds (e.g. 60 seconds in the default case).

After the `time.sleep` call, `scheduler._interval` seconds have elapsed, which means that the `scheduler_key` Redis key is set to expire in 10 more seconds (because of the call to `StrictRedis.expire` [here](https://github.com/ui/rq-scheduler/blob/master/rq_scheduler/scheduler.py#L299))

So, am I correct in my understanding that if `do_task_b()` takes more than 10 seconds, the `scheduler_key` will be expired by the time we iterate once more on the master `while True` loop?

Why do we want to expire the `scheduler_key` at all? Isn't this the index for all scheduled jobs?

**Comment by iafilatov** [comment]
The index for all scheduled jobs is different

    class Scheduler(object):
        scheduler_key = 'rq:scheduler'
        scheduled_jobs_key = 'rq:scheduler:scheduled_jobs'

If `do_task_b()` takes more than `scheduler._interval`, `scheduler_key` will indeed expire and it will become possible to bring up a second scheduler and mess things up. The original `run()` method doesn't have any additional tasks so the algorithm seems sound. The key might also expire if `enqueue_jobs()` takes to long, but that'd be an indication of a different problem. Why would you need to do a long-running task there anyway?

**Comment by Microserf** [comment]
This makes sense, thanks for the explanation.

The idea was to save money on Heroku by running, in a single app, the infinite loops for two of our scheduling systems. If it causes problems with the design used by rq-scheduler, I think the next best thing is implementing both loops as threads in the same process, for greater isolation.

**Comment by iafilatov** [comment]
That is possible, just keep in mind that `scheduler._install_signal_handlers()` can only be done in the main thread. Or you could try `multiprocessing`. I did a similar thing with multiprocessing once.
