### ISSUE TITLE
Documentation: enqueue_at and schedule need datetime.utcnow() to work correctly...

### ISSUE THREAD

**Issue by fleshgolem** [ui/rq-scheduler#94]
...not datetime.now(). I fought with this for well over 2 hours before I found the respective code. Maybe update the README so someone else does not have to

**Comment by dck** [comment]
Yep. The same for me. I needed to run periodic job and scheduler. Having executed `scheduler.schedule` with `datetime.now` I saw the workers didn't do anything. Tried to change on `utcnow()` just for test and it turned out it helped.

**Comment by selwin** [comment]
Yeah, a documentation on this UTC datetime requirement would most definitely help. Mind opening a PR?

**Comment by selwin** [comment]
Fixed in https://github.com/ui/rq-scheduler/commit/c23d4e0f5881de4e917e18316b20909ee4bf5daf
