### ISSUE TITLE
Questions about process of requeuing of jobs to queue and TTL of job

### ISSUE THREAD

**Issue by Edke** [ui/rq-scheduler#95]
Hello.

I'd like to ask about process rqscheduler re-queues repeating jobs. As I understand correctly from reading code and testing it's behavior, rq-scheduler does following:

1. it puts job in queue (unique UUID job id is created)
2. sleeps for defined interval
3. calculates which (repeating) jobs should be put again to queue
4. if so, re-queues existing job again to queue

Is this process correct ? 

According to our tests, TTL of job is set to -1 for job, that was already executed. In that case when you re-queue existing/executed job back to queue, it's TTL is not valid anymore.

Shouldn't rqworker just keep definition of job (function, arguments, definition of scheduling) in it's list and then calculate which job should go to queue (initially or repeatedly) and new job should be in both cases created (with proper TTL?)

### Our required design pattern (which is not working with current design):

We are scheduling also jobs, that:

- do every time same tasks again
- these tasks are to be created in certain time, when not possible to be executed (queue too big), their execution is not desired or even it is faulty to execute this task for example 30 seconds later
- when not executed on time, there will be new job executed few seconds later and will to same job

Maybe cron can do this better for us, but we need to schedule jobs more frequently than once per minute and also loading time of python2/django script has role when job starts as in cron based scheduling job actually starts few seconds later then scheduled as it takes some time for python script to start, on the other side when rq-scheduler puts loaded task to queue, it's executed immediately (when queue ready).

Example:

We create job, that should be executed every 15 seconds. When this job failes to start in that period of time, should be discarded (using TTL mechanism) in 12 seconds as missed start is not required (queue starts to fill), on 15th second new job will be started that will do everything needed to be executed in job before.

Thank you for any info regarding issue :)

**Comment by selwin** [comment]
What `rq-scheduler` does is pretty simple:
1. Creates an RQ job (not queued)
2. The `rqscheduler` script runs at a certain interval and to enqueue jobs whose desired time of execution is in the past

To achieve what you did, what you can do is create your own customized version of `rqscheduler` script. You should create your own `Scheduler` class that subclasses `scheduler.Scheduler` and override it's `run` method.
