### ISSUE TITLE
Creating a custom job_id doesn't work

### ISSUE THREAD

**Issue by glemmaPaul** [ui/rq-scheduler#96]
Hello all,

For some kind of reason the following doesn't work: 
```python
scheduler.schedule(datetime.datetime.now(), func,
                              args=[order.id],
                              kwargs=kwargs,
                              interval=30, id="myspecialID")
```

This is the exception I get:
```python
TypeError: schedule() got an unexpected keyword argument 'id'
```

Even though I look into the source and I see that `id` is a kwarg I can put in https://github.com/ui/rq-scheduler/blob/master/rq_scheduler/scheduler.py#L131-L132

Does anyone else have this same problem? Also, `id` is a reserved name, is it maybe better to call it `job_id`?

**Comment by selwin** [comment]
Support for id kwarg was added in August. The rq-scheduler package on PyPi is older and doesn't support id. Will try to cut a release soon.
